import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from "axios";

export default function Home() {

  const handleClick = () => {
    axios.get('/.netlify/functions/hello-world')
      .then(function (response) {
        // handle success
        console.log(response);
      })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={handleClick}>Hello world!</button>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
